#11 - control file fields
artipie/debian-adapter pull request #17
Opened 2020-12-29 14:58 UTC by olenagerasimova

Part of #11 
Added class to extract architecture from control file

2020-12-29 17:42 UTC, olegmoz requested changes
@olenagerasimova thanks, please see the comments

2020-12-29 17:42 UTC, olegmoz commented on src/main/java/com/artipie/debian/metadata/ControlField.java
> +    String[] value(String control);
@olenagerasimova I'd suggest to return a `List` here instead of arrays. Generally collections are easier to use

2020-12-29 17:42 UTC, olegmoz commented on src/main/java/com/artipie/debian/metadata/ControlField.java
> +    abstract class Wrap implements ControlField {
@olenagerasimova in Artipie `Wrap` classes usually are abstract decorators without any own functionality. So in context of our project I suggest to change class name.

2020-12-29 18:15 UTC, olenagerasimova commented
@olegmoz thanks, corrected

2020-12-30 07:49 UTC, olegmoz approved these changes
@olenagerasimova thanks, good to merge

2020-12-30 08:02 UTC, merged