#41 - update Release index
artipie/debian-adapter pull request #48
Opened 2021-02-17 07:15 UTC by olenagerasimova

Part of #41 
Update Release index with info of the Package index

2021-02-18 09:08 UTC, g4s8 requested changes
@olenagerasimova please check my questions

2021-02-18 09:08 UTC, g4s8 commented on src/main/java/com/artipie/debian/metadata/Release.java
> +                            )
@olenagerasimova we don't need to read the full package into the memory, since it's big memory consuming operation. It could be done this way:
 1. Unpak gzip package as a publisher (gzip could be unpacked by chunks), and providing downstream of unpacked bytes: `gzip-stream-> [unpack] -> unpacked-stream
 2. Calculate the size and sha256 of downstream (unpacked publisher) by reducing unpacked stream, similar to `ContentDigest`

2021-02-18 09:08 UTC, g4s8 commented on src/main/java/com/artipie/debian/metadata/Release.java
> +                        str -> Asto.addReplace(str, key.replace(".gz", ""), pair.getRight())
@olenagerasimova is it possible to read source value line by line instead loading full index file into memory, and replace matching lines on the fly?

2021-02-18 09:50 UTC, olenagerasimova commented on src/main/java/com/artipie/debian/metadata/Release.java
> +                        str -> Asto.addReplace(str, key.replace(".gz", ""), pair.getRight())
@g4s8 hm, it is, but it seems that I will have to copy the file into temp directory first and then read it with the help of `BufferedReader` (as it's done in rpm) line by line. Release index file cannot be very big - there are at most 30 supported architectures in debian - that's 60 lines plus 4 lines with other info. So, this file will have 65 lines max. Is it really necessary?

2021-02-18 09:51 UTC, olenagerasimova commented on src/main/java/com/artipie/debian/metadata/Release.java
> +                            )
@g4s8 yes, I see. Don't you mind if I do a separate class for it in another PR and then use this class here?

2021-02-18 10:31 UTC, olenagerasimova commented on src/main/java/com/artipie/debian/metadata/Release.java
> +                            )
@g4s8 please check #52

2021-02-19 08:33 UTC, g4s8 commented on src/main/java/com/artipie/debian/metadata/Release.java
> +                        str -> Asto.addReplace(str, key.replace(".gz", ""), pair.getRight())
@olenagerasimova got it, then it's fine to read 30 lines as a string. I thought this file could be big as package index files

2021-02-19 09:46 UTC, olenagerasimova commented on src/main/java/com/artipie/debian/metadata/Release.java
> +                            )
@g4s8 I do not see the real problem in reading gziped file into memory, it's compressed, should not be very large... I do not see a way of implementing what you are suggesting without copying `gz` into temp file first, as all the `commons.compress` works with files.

2021-02-25 06:01 UTC, olenagerasimova commented
@g4s8 could you please merge?

2021-02-25 10:22 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-02-25 10:22 UTC, merged