#41 - calc digest and size while unpacking
artipie/debian-adapter pull request #52
Opened 2021-02-18 10:30 UTC by olenagerasimova

Part of #41 
Unpack and calculate digest and size at the same time

2021-02-19 08:30 UTC, g4s8 requested changes
@olenagerasimova please check my comment

2021-02-19 08:30 UTC, g4s8 commented on src/main/java/com/artipie/debian/misc/UnpackedContent.java
> +                bytes -> {
@olenagerasimova please see the comment: https://github.com/artipie/debian-adapter/pull/48#discussion_r578243737  - we're still reading the full package content into the memory here, we need to unpack it by chunks to avoid high memory consumption

2021-02-20 09:12 UTC, olenagerasimova commented
@g4s8 thanks, added todo

2021-02-21 16:22 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-02-21 16:23 UTC, merged