#51 - Debian interface created
artipie/debian-adapter pull request #55
Opened 2021-03-01 14:55 UTC by olenagerasimova

Part of #51 
This is the interface I'd suggest exposing as sdk for our Chinese colleagues and preliminary implementation from the storage and repo config. We'll also need to add settings required by gpg-signing to the `Config`.

2021-03-01 15:20 UTC, g4s8 requested changes
@olenagerasimova thanks, please check my comment

2021-03-01 15:20 UTC, g4s8 commented on src/main/java/com/artipie/debian/Debian.java
> +    CompletionStage<Void> generateInRelease();
@olenagerasimova do we need to have two different methods for generating release index file? I think we can generate it with GPG signature by default and use a parameter to skip gpg if needed, e.g. `generateRelease(skip: false)`

2021-03-01 17:14 UTC, olenagerasimova commented on src/main/java/com/artipie/debian/Debian.java
> +    CompletionStage<Void> generateInRelease();
@g4s8 `Release` and `InRelease` files are two different files (the names are different), `Release` file requires `Release.gpg` file with the signature. From the [docs](https://wiki.debian.org/DebianRepository/Format#A.22Release.22_files)

> The file "dists/$DIST/InRelease" shall contain meta-information about the distribution and checksums for the indices, possibly signed with a GPG clearsign signature (for example created by "gpg -a -s --clearsign"). For older clients there can also be a "dists/$DIST/Release" file without any signature and the file "dists/$DIST/Release.gpg" with a detached GPG signature of the "Release" file, compatible with the format used by the GPG options "-a -b -s".

I think separate methods are more convenient, otherwise we also have to specify file type (name etc). Also, I think that gpg-settings should be optional, in this case we will not generate `Release.gpg` and `InRelease` at all.

2021-03-02 08:39 UTC, g4s8 commented on src/main/java/com/artipie/debian/Debian.java
> +    CompletionStage<Void> generateInRelease();
@olenagerasimova ok got it. Can you please add links to documentation to javadocs of these methods?

2021-03-02 11:03 UTC, olenagerasimova commented
@g4s8 thanks, I've extended javadoc

2021-03-02 11:47 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-03-02 11:47 UTC, merged