#51 - implemented Debian.Asto.updatePackages
artipie/debian-adapter pull request #69
Opened 2021-03-09 16:33 UTC by olenagerasimova

Part of #51
Implemented `Debian.Asto.updatePackages()`

2021-03-09 19:18 UTC, genryxy requested changes
@olenagerasimova thanks, one suggestion

2021-03-09 19:18 UTC, genryxy commented on src/test/java/com/artipie/debian/DebianTest.java
> +            "\n",
@olenagerasimova it looks too verbose. Probably to create some files for these three methods and after that read content of these files.

2021-03-10 07:42 UTC, olenagerasimova commented
@genryxy thanks, I've added todo, please, take a look

2021-03-10 11:38 UTC, genryxy approved these changes
@olenagerasimova thanks

2021-03-10 11:38 UTC, merged