Do not add duplicated info into Packages index
artipie/debian-adapter pull request #85
Opened 2021-03-22 14:11 UTC by olenagerasimova

Part of #74 
Implemented logic and added tests not to add duplicated info into `Packages` index. 
Will extract duplicated `if-else` statement into separate method is the next PR, also it will be necessary to remove old duplicated `.deb` packages with the help of the list returned by `decompressAppendCompress` method.

2021-03-22 20:57 UTC, genryxy requested changes
@olenagerasimova thanks, two comments

2021-03-22 20:57 UTC, genryxy commented on src/test/java/com/artipie/debian/metadata/UniquePackageTest.java
> +            ),
@olenagerasimova I'd suggest to create an array inside this method from three packages and parameterize test by specifying index of package which should be altered a bit by replacing some info

2021-03-22 20:57 UTC, genryxy commented on src/test/java/com/artipie/debian/metadata/UniquePackageTest.java
> +        );
@olenagerasimova also it is quite common to create key `new Key.From(UniquePackageTest.KEY)`. Probably to change type of static string to `Key` and use twice `string()` method in `appendsNewRecord()`

2021-03-23 06:38 UTC, olenagerasimova commented
@genryxy thanks, I do not see a way to parametrize tests though - not only initial packages differs, but the order of the packages in the assertions is also different...

2021-03-23 07:12 UTC, genryxy approved these changes
@olenagerasimova thanks 
I have idea how to do if there are always two packages for adding
`... .add(pkgs.get(idx), pkgs.get((idx + 1) % pkgs.size()))`
And check `(idx+2) % pkgs.size(), idx,  (idx + 1) % pkgs.size()`
Sorry for wrong suggestion.

2021-03-23 07:12 UTC, merged