Benchmarks for index merge
artipie/debian-adapter pull request #99
Opened 2021-04-19 11:56 UTC by olenagerasimova

Path of #98 
Added benchmark for index merge.

2021-04-19 13:46 UTC, g4s8 requested changes
@olenagerasimova please see my comments

2021-04-19 13:46 UTC, g4s8 commented on pom.xml
> +                <exclude>com/artipie/rpm/benchmarks/**/*</exclude>
@olenagerasimova `rpm` -> `debian` typo?

2021-04-19 13:46 UTC, g4s8 commented on src/main/java/com/artipie/debian/benchmarks/IndexMergeBench.java
> +        this.temp = Files.createTempDirectory("deb-index-merge-bench-res");
@olenagerasimova I'd suggest running benchmarks on memory storage to avoid unpredictable interruptions on IO calls.

2021-04-19 13:46 UTC, g4s8 commented on src/main/java/com/artipie/debian/benchmarks/IndexMergeBench.java
> +        List<InputStream> input = Collections.emptyList();
@olenagerasimova it looks like a preparation stage, not the benchmark's code

2021-04-20 06:55 UTC, olenagerasimova commented on src/main/java/com/artipie/debian/benchmarks/IndexMergeBench.java
> +        List<InputStream> input = Collections.emptyList();
@g4s8 I agree with here, but to separate this from the banchmark, I have to add setup in [invocation](http://javadox.com/org.openjdk.jmh/jmh-core/0.9/org/openjdk/jmh/annotations/Level.html#Invocation) level which does not seem a good idea in this case. Here is the javadoc:

> Invocation level: to be executed for each benchmark method execution.
> WARNING: HERE BE DRAGONS! THIS IS A SHARP TOOL. MAKE SURE YOU UNDERSTAND THE REASONING AND THE IMPLICATIONS OF THE WARNINGS BELOW BEFORE EVEN CONSIDERING USING THIS LEVEL.
> This level is only usable for benchmarks taking more than a millisecond per single Benchmark method invocation. It is a good idea to validate the impact for your case on ad-hoc basis as well.
> WARNING #1: Since we have to subtract the setup/teardown costs from the benchmark time, on this level, we have to timestamp *each* benchmark invocation. If the benchmarked method is small, then we saturate the system with timestamp requests, which introduce artificial latency, throughput, and scalability bottlenecks.
> WARNING #2: Since we measure individual invocation timings with this level, we probably set ourselves up for (coordinated) omission. That means the hiccups in measurement can be hidden from timing measurement, and can introduce surprising results. For example, when we use timings to understand the benchmark throughput, the omitted timing measurement will result in lower aggregate time, and fictionally *larger* throughput.
> WARNING #3: In order to maintain the same sharing behavior as other Levels, we sometimes have to synchronize (arbitrage) the access to State objects. Other levels do this outside the measurement, but at this level, we have to synchronize on *critical path*, further offsetting the measurement.
> WARNING #4: Current implementation allows the helper method execution at this Level to overlap with the benchmark invocation itself in order to simplify arbitrage. That matters in multi-threaded benchmarks, when one worker thread executing Benchmark method may observe other worker thread already calling TearDown for the same object.

And BTW in rpm-adapter I've missed the mistake: there we have to use `invocation` level instead of `iteration`.

2021-04-20 07:00 UTC, olenagerasimova commented
@g4s8 thanks, corrected and answered

2021-04-20 08:46 UTC, g4s8 requested changes

2021-04-20 08:46 UTC, g4s8 commented on src/main/java/com/artipie/debian/benchmarks/IndexMergeBench.java
> +        List<InputStream> input = Collections.emptyList();
@olenagerasimova I see. In that case I think we can prepare some immutable data as byte arrays in global `BeforeEach` and pass wrap it with input streams in benchmark's code, because loading a file from disk is comparable by time with `merge()` calls and depends on many unpredictable environment events.

2021-04-20 09:22 UTC, olenagerasimova commented
@g4s8 thanks, done

2021-04-20 13:37 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-04-20 13:37 UTC, merged